import type { NewExerciseInput } from '../db/exercises';

export const SEED_EXERCISES: NewExerciseInput[] = [
  // ─── CHEST ───────────────────────────────────────────────────────────────────
  {
    name: 'Barbell Bench Press',
    exercise_type: 'compound',
    primary_muscles: ['chest'],
    secondary_muscles: ['front delts', 'triceps'],
    alt_names: ['Bench Press', 'Flat Bench'],
    description: '',
    weight_direction: 1,
  },
  {
    name: 'Incline Barbell Bench Press',
    exercise_type: 'compound',
    primary_muscles: ['chest'],
    secondary_muscles: ['front delts', 'triceps'],
    alt_names: ['Incline Bench Press'],
    description: '',
    weight_direction: 1,
  },
  {
    name: 'Decline Barbell Bench Press',
    exercise_type: 'compound',
    primary_muscles: ['chest'],
    secondary_muscles: ['front delts', 'triceps'],
    alt_names: ['Decline Bench Press'],
    description: '',
    weight_direction: 1,
  },
  {
    name: 'Dumbbell Bench Press',
    exercise_type: 'compound',
    primary_muscles: ['chest'],
    secondary_muscles: ['front delts', 'triceps'],
    alt_names: ['DB Bench Press'],
    description: '',
    weight_direction: 1,
  },
  {
    name: 'Incline Dumbbell Bench Press',
    exercise_type: 'compound',
    primary_muscles: ['chest'],
    secondary_muscles: ['front delts', 'triceps'],
    alt_names: ['Incline DB Press'],
    description: '',
    weight_direction: 1,
  },
  {
    name: 'Decline Dumbbell Bench Press',
    exercise_type: 'compound',
    primary_muscles: ['chest'],
    secondary_muscles: ['front delts', 'triceps'],
    alt_names: ['Decline DB Press'],
    description: '',
    weight_direction: 1,
  },
  {
    name: 'Dumbbell Fly',
    exercise_type: 'isolation',
    primary_muscles: ['chest'],
    secondary_muscles: ['front delts'],
    alt_names: ['DB Fly', 'Flat Fly'],
    description: '',
    weight_direction: 1,
  },
  {
    name: 'Incline Dumbbell Fly',
    exercise_type: 'isolation',
    primary_muscles: ['chest'],
    secondary_muscles: ['front delts'],
    alt_names: ['Incline DB Fly'],
    description: '',
    weight_direction: 1,
  },
  {
    name: 'Cable Fly',
    exercise_type: 'isolation',
    primary_muscles: ['chest'],
    secondary_muscles: ['front delts'],
    alt_names: ['Cable Crossover'],
    description: '',
    weight_direction: 1,
  },
  {
    name: 'Low-to-High Cable Fly',
    exercise_type: 'isolation',
    primary_muscles: ['chest'],
    secondary_muscles: ['front delts'],
    alt_names: [],
    description: '',
    weight_direction: 1,
  },
  {
    name: 'High-to-Low Cable Fly',
    exercise_type: 'isolation',
    primary_muscles: ['chest'],
    secondary_muscles: ['front delts'],
    alt_names: [],
    description: '',
    weight_direction: 1,
  },
  {
    name: 'Push-Up',
    exercise_type: 'compound',
    primary_muscles: ['chest'],
    secondary_muscles: ['front delts', 'triceps'],
    alt_names: ['Press-Up'],
    description: '',
    weight_direction: 1,
  },
  {
    name: 'Wide-Grip Push-Up',
    exercise_type: 'compound',
    primary_muscles: ['chest'],
    secondary_muscles: ['front delts', 'triceps'],
    alt_names: [],
    description: '',
    weight_direction: 1,
  },
  {
    name: 'Decline Push-Up',
    exercise_type: 'compound',
    primary_muscles: ['chest'],
    secondary_muscles: ['front delts', 'triceps'],
    alt_names: [],
    description: '',
    weight_direction: 1,
  },
  {
    name: 'Diamond Push-Up',
    exercise_type: 'compound',
    primary_muscles: ['triceps'],
    secondary_muscles: ['chest', 'front delts'],
    alt_names: ['Close-Grip Push-Up'],
    description: '',
    weight_direction: 1,
  },
  {
    name: 'Dip',
    exercise_type: 'compound',
    primary_muscles: ['chest'],
    secondary_muscles: ['front delts', 'triceps'],
    alt_names: ['Weighted Dip'],
    description: '',
    weight_direction: 1,
  },
  {
    name: 'Machine Chest Press',
    exercise_type: 'compound',
    primary_muscles: ['chest'],
    secondary_muscles: ['front delts', 'triceps'],
    alt_names: ['Chest Press Machine'],
    description: '',
    weight_direction: 1,
  },
  {
    name: 'Pec Deck',
    exercise_type: 'isolation',
    primary_muscles: ['chest'],
    secondary_muscles: [],
    alt_names: ['Machine Fly', 'Butterfly Machine'],
    description: '',
    weight_direction: 1,
  },
  {
    name: 'Smith Machine Bench Press',
    exercise_type: 'compound',
    primary_muscles: ['chest'],
    secondary_muscles: ['front delts', 'triceps'],
    alt_names: [],
    description: '',
    weight_direction: 1,
  },
  {
    name: 'Landmine Press',
    exercise_type: 'compound',
    primary_muscles: ['chest', 'shoulders'],
    secondary_muscles: ['triceps'],
    alt_names: [],
    description: '',
    weight_direction: 1,
  },
  {
    name: 'Dumbbell Pullover',
    exercise_type: 'accessory',
    primary_muscles: ['chest'],
    secondary_muscles: ['lats'],
    alt_names: [],
    description: '',
    weight_direction: 1,
  },

  // ────────────────────────────────────────────────────────────────────────
  {
    name: 'Barbell Deadlift',
    exercise_type: 'compound',
    primary_muscles: ['lower back', 'lats'],
    secondary_muscles: ['glutes', 'hamstrings', 'traps'],
    alt_names: ['Deadlift', 'Conventional Deadlift'],
    description: '',
    weight_direction: 1,
  },
  {
    name: 'Romanian Deadlift',
    exercise_type: 'compound',
    primary_muscles: ['hamstrings', 'glutes'],
    secondary_muscles: ['lower back'],
    alt_names: ['RDL', 'Stiff-Leg Deadlift'],
    description: '',
    weight_direction: 1,
  },
  {
    name: 'Trap Bar Deadlift',
    exercise_type: 'compound',
    primary_muscles: ['quads', 'glutes'],
    secondary_muscles: ['lower back', 'hamstrings'],
    alt_names: ['Hex Bar Deadlift'],
    description: '',
    weight_direction: 1,
  },
  {
    name: 'Pull-Up',
    exercise_type: 'compound',
    primary_muscles: ['back'],
    secondary_muscles: ['biceps', 'forearms'],
    alt_names: [],
    description: '',
    weight_direction: 1,
  },
  {
    name: 'Chin-Up',
    exercise_type: 'compound',
    primary_muscles: ['back', 'biceps'],
    secondary_muscles: ['forearms'],
    alt_names: [],
    description: '',
    weight_direction: 1,
  },
  {
    name: 'Lat Pulldown',
    exercise_type: 'compound',
    primary_muscles: ['back'],
    secondary_muscles: ['biceps', 'forearms'],
    alt_names: ['Wide-Grip Lat Pulldown'],
    description: '',
    weight_direction: 1,
  },
  {
    name: 'Barbell Bent-Over Row',
    exercise_type: 'compound',
    primary_muscles: ['back'],
    secondary_muscles: ['biceps', 'forearms'],
    alt_names: ['Barbell Row', 'Pendlay Row'],
    description: '',
    weight_direction: 1,
  },
  {
    name: 'Dumbbell Row',
    exercise_type: 'compound',
    primary_muscles: ['lats', 'rhomboids'],
    secondary_muscles: ['biceps', 'traps'],
    alt_names: ['Single-Arm Dumbbell Row', 'DB Row'],
    description: '',
    weight_direction: 1,
  },
  {
    name: 'T-Bar Row',
    exercise_type: 'compound',
    primary_muscles: ['lats', 'rhomboids'],
    secondary_muscles: ['biceps', 'traps'],
    alt_names: ['Landmine Row'],
    description: '',
    weight_direction: 1,
  },
  {
    name: 'Seated Cable Row',
    exercise_type: 'compound',
    primary_muscles: ['lats', 'rhomboids'],
    secondary_muscles: ['biceps'],
    alt_names: ['Cable Row'],
    description: '',
    weight_direction: 1,
  },
  {
    name: 'Wide-Grip Cable Row',
    exercise_type: 'compound',
    primary_muscles: ['lats', 'rhomboids'],
    secondary_muscles: ['biceps'],
    alt_names: [],
    description: '',
    weight_direction: 1,
  },
  {
    name: 'Chest-Supported Row',
    exercise_type: 'compound',
    primary_muscles: ['rhomboids', 'lats'],
    secondary_muscles: ['biceps', 'rear delts'],
    alt_names: ['Incline Dumbbell Row'],
    description: '',
    weight_direction: 1,
  },
  {
    name: 'Machine Row',
    exercise_type: 'acessory',
    primary_muscles: ['lats', 'rhomboids'],
    secondary_muscles: ['biceps'],
    alt_names: ['Hammer Strength Row'],
    description: '',
    weight_direction: 1,
  },
  {
    name: 'Inverted Row',
    exercise_type: 'compound',
    primary_muscles: ['rhomboids', 'lats'],
    secondary_muscles: ['biceps'],
    alt_names: ['Australian Pull-Up', 'Bodyweight Row'],
    description: '',
    weight_direction: 1,
  },
  {
    name: 'Barbell Shrug',
    exercise_type: 'accessory',
    primary_muscles: ['traps'],
    secondary_muscles: [],
    alt_names: [],
    description: '',
    weight_direction: 1,
  },
  {
    name: 'Dumbbell Shrug',
    exercise_type: 'accessory',
    primary_muscles: ['traps'],
    secondary_muscles: [],
    alt_names: [],
    description: '',
    weight_direction: 1,
  },
  {
    name: 'Good Morning',
    exercise_type: 'acessory',
    primary_muscles: ['lower back', 'hamstrings'],
    secondary_muscles: ['glutes'],
    alt_names: [],
    description: '',
    weight_direction: 1,
  },
  {
    name: 'Back Extension',
    exercise_type: 'accessory',
    primary_muscles: ['lower back'],
    secondary_muscles: ['glutes', 'hamstrings'],
    alt_names: ['Hyperextension', '45° Back Extension'],
    description: '',
    weight_direction: 1,
  },
  {
    name: 'Straight-Arm Pulldown',
    exercise_type: 'isolation',
    primary_muscles: ['lats'],
    secondary_muscles: ['biceps', 'forearms'],
    alt_names: ['Straight-Arm Cable Pulldown'],
    description: '',
    weight_direction: 1,
  },
  {
    name: 'Face Pull',
    exercise_type: 'accessory',
    primary_muscles: ['rear delts', 'rhomboids'],
    secondary_muscles: ['traps'],
    alt_names: ['Cable Face Pull'],
    description: '',
    weight_direction: 1,
  },
  {
    name: 'Assisted Pull-Up Machine',
    exercise_type: 'compound',
    primary_muscles: ['lats'],
    secondary_muscles: ['biceps', 'rhomboids', 'forearms'],
    alt_names: ['Assisted Pull-Up'],
    description: '',
    weight_direction: -1,
  },
  {
    name: 'Kroc Row',
    exercise_type: 'accessory',
    primary_muscles: ['lats', 'rhomboids'],
    secondary_muscles: ['biceps', 'traps'],
    alt_names: [],
    description: '',
    weight_direction: 1,
  },
  {
    name: 'Snatch-Grip Deadlift',
    exercise_type: 'compound',
    primary_muscles: ['lower back', 'traps'],
    secondary_muscles: ['glutes', 'hamstrings'],
    alt_names: [],
    description: '',
    weight_direction: 1,
  },
  {
    name: 'Cable Pullthrough',
    exercise_type: 'accessory',
    primary_muscles: ['glutes', 'lower back'],
    secondary_muscles: ['hamstrings'],
    alt_names: [],
    description: '',
    weight_direction: 1,
  },
  {
    name: 'Dumbbell Romanian Deadlift',
    exercise_type: 'compound',
    primary_muscles: ['hamstrings', 'glutes'],
    secondary_muscles: ['lower back'],
    alt_names: ['DB RDL'],
    description: '',
    weight_direction: 1,
  },
  {
    name: 'Reverse Hyperextension',
    exercise_type: 'accessory',
    primary_muscles: ['glutes'],
    secondary_muscles: ['lower back', 'hamstrings'],
    alt_names: ['Reverse Hyper'],
    description: '',
    weight_direction: 1,
  },
  {
    name: 'Cable Shrug',
    exercise_type: 'accessory',
    primary_muscles: ['traps'],
    secondary_muscles: [],
    alt_names: [],
    description: '',
    weight_direction: 1,
  },

  // ─── SHOULDERS ────────────────────────────────────────────────────────────────
  {
    name: 'Barbell Overhead Press',
    exercise_type: 'compound',
    primary_muscles: ['shoulders'],
    secondary_muscles: ['traps', 'triceps'],
    alt_names: ['Military Press', 'OHP', 'Overhead Press'],
    description: '',
    weight_direction: 1,
  },
  {
    name: 'Dumbbell Shoulder Press',
    exercise_type: 'compound',
    primary_muscles: ['shoulders'],
    secondary_muscles: ['triceps'],
    alt_names: ['DB Shoulder Press', 'DB Overhead Press'],
    description: '',
    weight_direction: 1,
  },
  {
    name: 'Arnold Press',
    exercise_type: 'compound',
    primary_muscles: ['shoulders'],
    secondary_muscles: ['triceps'],
    alt_names: [],
    description: '',
    weight_direction: 1,
  },
  {
    name: 'Push Press',
    exercise_type: 'compound',
    primary_muscles: ['shoulders'],
    secondary_muscles: ['traps', 'triceps'],
    alt_names: [],
    description: '',
    weight_direction: 1,
  },
  {
    name: 'Machine Shoulder Press',
    exercise_type: 'compound',
    primary_muscles: ['shoulders'],
    secondary_muscles: ['triceps'],
    alt_names: ['Seated Machine Press'],
    description: '',
    weight_direction: 1,
  },
  {
    name: 'Smith Machine Overhead Press',
    exercise_type: 'compound',
    primary_muscles: ['shoulders'],
    secondary_muscles: ['triceps'],
    alt_names: [],
    description: '',
    weight_direction: 1,
  },
  {
    name: 'Lateral Raise',
    exercise_type: 'isolation',
    primary_muscles: ['side delts'],
    secondary_muscles: [],
    alt_names: ['Dumbbell Lateral Raise', 'Side Raise'],
    description: '',
    weight_direction: 1,
  },
  {
    name: 'Cable Lateral Raise',
    exercise_type: 'isolation',
    primary_muscles: ['side delts'],
    secondary_muscles: [],
    alt_names: [],
    description: '',
    weight_direction: 1,
  },
  {
    name: 'Machine Lateral Raise',
    exercise_type: 'isolation',
    primary_muscles: ['side delts'],
    secondary_muscles: [],
    alt_names: [],
    description: '',
    weight_direction: 1,
  },
  {
    name: 'Dumbbell Front Raise',
    exercise_type: 'isolation',
    primary_muscles: ['front delts'],
    secondary_muscles: [],
    alt_names: ['Front Raise'],
    description: '',
    weight_direction: 1,
  },
  {
    name: 'Cable Front Raise',
    exercise_type: 'isolation',
    primary_muscles: ['front delts'],
    secondary_muscles: [],
    alt_names: [],
    description: '',
    weight_direction: 1,
  },
  {
    name: 'Plate Front Raise',
    exercise_type: 'isolation',
    primary_muscles: ['front delts'],
    secondary_muscles: [],
    alt_names: [],
    description: '',
    weight_direction: 1,
  },
  {
    name: 'Reverse Dumbbell Fly',
    exercise_type: 'isolation',
    primary_muscles: ['rear delts'],
    secondary_muscles: ['rhomboids'],
    alt_names: ['Bent-Over Lateral Raise', 'Rear Delt Fly'],
    description: '',
    weight_direction: 1,
  },
  {
    name: 'Reverse Pec Deck',
    exercise_type: 'isolation',
    primary_muscles: ['rear delts'],
    secondary_muscles: ['rhomboids'],
    alt_names: ['Rear Delt Machine'],
    description: '',
    weight_direction: 1,
  },
  {
    name: 'Cable Reverse Fly',
    exercise_type: 'isolation',
    primary_muscles: ['rear delts'],
    secondary_muscles: ['rhomboids'],
    alt_names: [],
    description: '',
    weight_direction: 1,
  },
  {
    name: 'Barbell Upright Row',
    exercise_type: 'accessory',
    primary_muscles: ['side delts', 'traps'],
    secondary_muscles: ['front delts', 'biceps'],
    alt_names: ['Upright Row'],
    description: '',
    weight_direction: 1,
  },
  {
    name: 'Dumbbell Upright Row',
    exercise_type: 'accessory',
    primary_muscles: ['side delts', 'traps'],
    secondary_muscles: ['front delts', 'biceps'],
    alt_names: [],
    description: '',
    weight_direction: 1,
  },
  {
    name: 'Y-Raise',
    exercise_type: 'accessory',
    primary_muscles: ['rear delts'],
    secondary_muscles: ['rhomboids', 'traps'],
    alt_names: ['Dumbbell Y-Raise', 'Prone Y-Raise'],
    description: '',
    weight_direction: 1,
  },
  {
    name: 'Cuban Press',
    exercise_type: 'accessory',
    primary_muscles: ['rear delts', 'side delts'],
    secondary_muscles: ['front delts'],
    alt_names: [],
    description: '',
    weight_direction: 1,
  },
  {
    name: 'Landmine Lateral Raise',
    exercise_type: 'isolation',
    primary_muscles: ['side delts'],
    secondary_muscles: [],
    alt_names: [],
    description: '',
    weight_direction: 1,
  },

  // ─── LEGS ─────────────────────────────────────────────────────────────────────
  {
    name: 'Barbell Back Squat',
    exercise_type: 'compound',
    primary_muscles: ['legs'],
    secondary_muscles: ['lower back', 'core'],
    alt_names: ['Back Squat', 'Squat'],
    description: '',
    weight_direction: 1,
  },
  {
    name: 'Front Squat (Barbell)',
    exercise_type: 'compound',
    primary_muscles: ['legs'],
    secondary_muscles: ['lower back', 'core'],
    alt_names: [],
    description: '',
    weight_direction: 1,
  },
  {
    name: 'Goblet Squat',
    exercise_type: 'compound',
    primary_muscles: ['legs'],
    secondary_muscles: ['core'],
    alt_names: [],
    description: '',
    weight_direction: 1,
  },
  {
    name: 'Box Squat',
    exercise_type: 'compound',
    primary_muscles: ['legs'],
    secondary_muscles: ['lower back', 'core'],
    alt_names: [],
    description: '',
    weight_direction: 1,
  },
  {
    name: 'Pause Squat',
    exercise_type: 'compound',
    primary_muscles: ['legs'],
    secondary_muscles: ['lower back', 'core'],
    alt_names: [],
    description: '',
    weight_direction: 1,
  },
  {
    name: 'Hack Squat',
    exercise_type: 'compound',
    primary_muscles: ['quads'],
    secondary_muscles: ['glutes'],
    alt_names: ['Machine Hack Squat'],
    description: '',
    weight_direction: 1,
  },
  {
    name: 'Smith Machine Squat',
    exercise_type: 'compound',
    primary_muscles: ['quads', 'glutes'],
    secondary_muscles: ['hamstrings'],
    alt_names: [],
    description: '',
    weight_direction: 1,
  },
  {
    name: 'Bulgarian Split Squat',
    exercise_type: 'compound',
    primary_muscles: ['quads', 'glutes'],
    secondary_muscles: ['hamstrings'],
    alt_names: ['Rear-Foot Elevated Split Squat', 'RFESS'],
    description: '',
    weight_direction: 1,
  },
  {
    name: 'Leg Press',
    exercise_type: 'compound',
    primary_muscles: ['legs'],
    secondary_muscles: [],
    alt_names: [],
    description: '',
    weight_direction: 1,
  },
  {
    name: 'Single-Leg Press',
    exercise_type: 'compound',
    primary_muscles: ['quads', 'glutes'],
    secondary_muscles: ['hamstrings'],
    alt_names: [],
    description: '',
    weight_direction: 1,
  },
  {
    name: 'Barbell Lunge',
    exercise_type: 'compound',
    primary_muscles: ['legs'],
    secondary_muscles: ['lower back', 'core'],
    alt_names: [],
    description: '',
    weight_direction: 1,
  },
  {
    name: 'Dumbbell Lunge',
    exercise_type: 'compound',
    primary_muscles: ['legs'],
    secondary_muscles: ['lower back', 'core'],
    alt_names: ['Walking Lunge'],
    description: '',
    weight_direction: 1,
  },
  {
    name: 'Reverse Lunge',
    exercise_type: 'compound',
    primary_muscles: ['legs'],
    secondary_muscles: ['lower back', 'core'],
    alt_names: ['Step-Back Lunge'],
    description: '',
    weight_direction: 1,
  },
  {
    name: 'Lateral Lunge',
    exercise_type: 'compound',
    primary_muscles: ['legs'],
    secondary_muscles: ['lower back', 'core'],
    alt_names: ['Side Lunge'],
    description: '',
    weight_direction: 1,
  },
  {
    name: 'Step-Up',
    exercise_type: 'compound',
    primary_muscles: ['quads', 'glutes'],
    secondary_muscles: ['hamstrings'],
    alt_names: ['Box Step-Up'],
    description: '',
    weight_direction: 1,
  },
  {
    name: 'Leg Extension',
    exercise_type: 'isolation',
    primary_muscles: ['quads'],
    secondary_muscles: [],
    alt_names: ['Machine Leg Extension'],
    description: '',
    weight_direction: 1,
  },
  {
    name: 'Lying Leg Curl',
    exercise_type: 'isolation',
    primary_muscles: ['hamstrings'],
    secondary_muscles: [],
    alt_names: ['Prone Leg Curl'],
    description: '',
    weight_direction: 1,
  },
  {
    name: 'Seated Leg Curl',
    exercise_type: 'isolation',
    primary_muscles: ['hamstrings'],
    secondary_muscles: [],
    alt_names: ['Machine Leg Curl'],
    description: '',
    weight_direction: 1,
  },
  {
    name: 'Nordic Curl',
    exercise_type: 'isolation',
    primary_muscles: ['hamstrings'],
    secondary_muscles: [],
    alt_names: ['Nordic Hamstring Curl'],
    description: '',
    weight_direction: 1,
  },
  {
    name: 'Single-Leg Romanian Deadlift',
    exercise_type: 'compound',
    primary_muscles: ['hamstrings', 'glutes'],
    secondary_muscles: ['lower back'],
    alt_names: ['Single-Leg RDL', 'SL RDL'],
    description: '',
    weight_direction: 1,
  },
  {
    name: 'Standing Calf Raise',
    exercise_type: 'isolation',
    primary_muscles: ['calves'],
    secondary_muscles: [],
    alt_names: ['Calf Raise'],
    description: '',
    weight_direction: 1,
  },
  {
    name: 'Seated Calf Raise',
    exercise_type: 'isolation',
    primary_muscles: ['calves'],
    secondary_muscles: [],
    alt_names: [],
    description: '',
    weight_direction: 1,
  },
  {
    name: 'Single-Leg Calf Raise',
    exercise_type: 'isolation',
    primary_muscles: ['calves'],
    secondary_muscles: [],
    alt_names: [],
    description: '',
    weight_direction: 1,
  },
  {
    name: 'Donkey Calf Raise',
    exercise_type: 'isolation',
    primary_muscles: ['calves'],
    secondary_muscles: [],
    alt_names: [],
    description: '',
    weight_direction: 1,
  },
  {
    name: 'Barbell Hip Thrust',
    exercise_type: 'compound',
    primary_muscles: ['glutes'],
    secondary_muscles: ['hamstrings'],
    alt_names: ['Hip Thrust'],
    description: '',
    weight_direction: 1,
  },
  {
    name: 'Dumbbell Hip Thrust',
    exercise_type: 'compound',
    primary_muscles: ['glutes'],
    secondary_muscles: ['hamstrings'],
    alt_names: [],
    description: '',
    weight_direction: 1,
  },
  {
    name: 'Glute Bridge',
    exercise_type: 'accessory',
    primary_muscles: ['glutes'],
    secondary_muscles: ['hamstrings'],
    alt_names: ['Barbell Glute Bridge'],
    description: '',
    weight_direction: 1,
  },
  {
    name: 'Single-Leg Hip Thrust',
    exercise_type: 'compound',
    primary_muscles: ['glutes'],
    secondary_muscles: ['hamstrings'],
    alt_names: [],
    description: '',
    weight_direction: 1,
  },
  {
    name: 'Adductor Machine',
    exercise_type: 'isolation',
    primary_muscles: ['adductors'],
    secondary_muscles: [],
    alt_names: ['Inner Thigh Machine'],
    description: '',
    weight_direction: 1,
  },
  {
    name: 'Abductor Machine',
    exercise_type: 'isolation',
    primary_muscles: ['glutes'],
    secondary_muscles: [],
    alt_names: ['Outer Thigh Machine', 'Hip Abductor Machine'],
    description: '',
    weight_direction: 1,
  },
  {
    name: 'Cable Kickback',
    exercise_type: 'isolation',
    primary_muscles: ['glutes'],
    secondary_muscles: [],
    alt_names: ['Glute Kickback'],
    description: '',
    weight_direction: 1,
  },
  {
    name: 'Pistol Squat',
    exercise_type: 'compound',
    primary_muscles: ['quads', 'glutes'],
    secondary_muscles: ['hamstrings'],
    alt_names: ['Single-Leg Squat'],
    description: '',
    weight_direction: 1,
  },
  {
    name: 'Zercher Squat',
    exercise_type: 'compound',
    primary_muscles: ['legs'],
    secondary_muscles: ['lower back', 'core'],
    alt_names: [],
    description: '',
    weight_direction: 1,
  },
  {
    name: 'Sumo Squat',
    exercise_type: 'compound',
    primary_muscles: ['legs'],
    secondary_muscles: ['lower back', 'core'],
    alt_names: ['Plie Squat'],
    description: '',
    weight_direction: 1,
  },

  // ─── BICEPS ───────────────────────────────────────────────────────────────────
  {
    name: 'Barbell Curl',
    exercise_type: 'isolation',
    primary_muscles: ['biceps'],
    secondary_muscles: ['forearms'],
    alt_names: ['Straight Bar Curl'],
    description: '',
    weight_direction: 1,
  },
  {
    name: 'Dumbbell Curl',
    exercise_type: 'isolation',
    primary_muscles: ['biceps'],
    secondary_muscles: ['forearms'],
    alt_names: ['Alternating Dumbbell Curl', 'DB Curl'],
    description: '',
    weight_direction: 1,
  },
  {
    name: 'Hammer Curl',
    exercise_type: 'isolation',
    primary_muscles: ['biceps', 'forearms'],
    secondary_muscles: [],
    alt_names: ['Neutral-Grip Curl'],
    description: '',
    weight_direction: 1,
  },
  {
    name: 'Preacher Curl',
    exercise_type: 'isolation',
    primary_muscles: ['biceps'],
    secondary_muscles: [],
    alt_names: ['EZ-Bar Preacher Curl', 'Barbell Preacher Curl'],
    description: '',
    weight_direction: 1,
  },
  {
    name: 'Incline Dumbbell Curl',
    exercise_type: 'isolation',
    primary_muscles: ['biceps'],
    secondary_muscles: [],
    alt_names: [],
    description: '',
    weight_direction: 1,
  },
  {
    name: 'Concentration Curl',
    exercise_type: 'isolation',
    primary_muscles: ['biceps'],
    secondary_muscles: [],
    alt_names: [],
    description: '',
    weight_direction: 1,
  },
  {
    name: 'Cable Curl',
    exercise_type: 'isolation',
    primary_muscles: ['biceps'],
    secondary_muscles: ['forearms'],
    alt_names: ['Cable Bicep Curl'],
    description: '',
    weight_direction: 1,
  },
  {
    name: 'Cable Hammer Curl',
    exercise_type: 'isolation',
    primary_muscles: ['biceps', 'forearms'],
    secondary_muscles: [],
    alt_names: ['Rope Cable Curl'],
    description: '',
    weight_direction: 1,
  },
  {
    name: 'EZ-Bar Curl',
    exercise_type: 'isolation',
    primary_muscles: ['biceps'],
    secondary_muscles: ['forearms'],
    alt_names: [],
    description: '',
    weight_direction: 1,
  },
  {
    name: 'Machine Curl',
    exercise_type: 'isolation',
    primary_muscles: ['biceps'],
    secondary_muscles: [],
    alt_names: ['Machine Bicep Curl'],
    description: '',
    weight_direction: 1,
  },
  {
    name: 'Reverse Curl',
    exercise_type: 'isolation',
    primary_muscles: ['forearms', 'biceps'],
    secondary_muscles: [],
    alt_names: ['Reverse Barbell Curl'],
    description: '',
    weight_direction: 1,
  },
  {
    name: 'Drag Curl',
    exercise_type: 'isolation',
    primary_muscles: ['biceps'],
    secondary_muscles: [],
    alt_names: [],
    description: '',
    weight_direction: 1,
  },
  {
    name: 'Spider Curl',
    exercise_type: 'isolation',
    primary_muscles: ['biceps'],
    secondary_muscles: [],
    alt_names: [],
    description: '',
    weight_direction: 1,
  },
  {
    name: 'Zottman Curl',
    exercise_type: 'isolation',
    primary_muscles: ['biceps', 'forearms'],
    secondary_muscles: [],
    alt_names: [],
    description: '',
    weight_direction: 1,
  },
  {
    name: 'Cross-Body Hammer Curl',
    exercise_type: 'isolation',
    primary_muscles: ['biceps', 'forearms'],
    secondary_muscles: [],
    alt_names: [],
    description: '',
    weight_direction: 1,
  },
  {
    name: 'Bayesian Curl',
    exercise_type: 'isolation',
    primary_muscles: ['biceps'],
    secondary_muscles: [],
    alt_names: ['Cable Bayesian Curl'],
    description: '',
    weight_direction: 1,
  },
  {
    name: 'Dumbbell Preacher Curl',
    exercise_type: 'isolation',
    primary_muscles: ['biceps'],
    secondary_muscles: [],
    alt_names: [],
    description: '',
    weight_direction: 1,
  },

  // ─── TRICEPS ──────────────────────────────────────────────────────────────────
  {
    name: 'Close-Grip Bench Press',
    exercise_type: 'compound',
    primary_muscles: ['triceps'],
    secondary_muscles: ['chest', 'front delts'],
    alt_names: ['CGBP'],
    description: '',
    weight_direction: 1,
  },
  {
    name: 'Skull Crusher',
    exercise_type: 'accessory',
    primary_muscles: ['triceps'],
    secondary_muscles: [],
    alt_names: ['Lying Tricep Extension', 'EZ-Bar Skull Crusher', 'Barbell Skull Crusher'],
    description: '',
    weight_direction: 1,
  },
  {
    name: 'Dumbbell Skull Crusher',
    exercise_type: 'accessory',
    primary_muscles: ['triceps'],
    secondary_muscles: [],
    alt_names: [],
    description: '',
    weight_direction: 1,
  },
  {
    name: 'Tricep Pushdown (Bar)',
    exercise_type: 'isolation',
    primary_muscles: ['triceps'],
    secondary_muscles: [],
    alt_names: ['Cable Pushdown', 'Straight Bar Pushdown'],
    description: '',
    weight_direction: 1,
  },
  {
    name: 'Tricep Pushdown (Rope)',
    exercise_type: 'isolation',
    primary_muscles: ['triceps'],
    secondary_muscles: [],
    alt_names: ['Rope Pushdown', 'Cable Rope Pushdown'],
    description: '',
    weight_direction: 1,
  },
  {
    name: 'Overhead Tricep Extension (Barbell)',
    exercise_type: 'isolation',
    primary_muscles: ['triceps'],
    secondary_muscles: [],
    alt_names: ['French Press'],
    description: '',
    weight_direction: 1,
  },
  {
    name: 'Overhead Tricep Extension (Dumbbell)',
    exercise_type: 'isolation',
    primary_muscles: ['triceps'],
    secondary_muscles: [],
    alt_names: ['Dumbbell French Press'],
    description: '',
    weight_direction: 1,
  },
  {
    name: 'Overhead Tricep Extension (Cable)',
    exercise_type: 'isolation',
    primary_muscles: ['triceps'],
    secondary_muscles: [],
    alt_names: ['Cable Overhead Extension'],
    description: '',
    weight_direction: 1,
  },
  {
    name: 'Tricep Dip',
    exercise_type: 'compound',
    primary_muscles: ['triceps'],
    secondary_muscles: ['chest', 'front delts'],
    alt_names: ['Bench Dip'],
    description: '',
    weight_direction: 1,
  },
  {
    name: 'Tricep Kickback',
    exercise_type: 'isolation',
    primary_muscles: ['triceps'],
    secondary_muscles: [],
    alt_names: ['Dumbbell Kickback'],
    description: '',
    weight_direction: 1,
  },
  {
    name: 'Single-Arm Overhead Extension',
    exercise_type: 'isolation',
    primary_muscles: ['triceps'],
    secondary_muscles: [],
    alt_names: [],
    description: '',
    weight_direction: 1,
  },
  {
    name: 'Single-Arm Pushdown',
    exercise_type: 'isolation',
    primary_muscles: ['triceps'],
    secondary_muscles: [],
    alt_names: [],
    description: '',
    weight_direction: 1,
  },
  {
    name: 'Bradford Press',
    exercise_type: 'compound',
    primary_muscles: ['front delts', 'side delts'],
    secondary_muscles: ['triceps'],
    alt_names: [],
    description: '',
    weight_direction: 1,
  },
  {
    name: 'Assisted Tricep Dip Machine',
    exercise_type: 'compound',
    primary_muscles: ['triceps'],
    secondary_muscles: ['chest', 'front delts'],
    alt_names: [],
    description: '',
    weight_direction: -1,
  },

  // ─── FOREARMS ─────────────────────────────────────────────────────────────────
  {
    name: 'Wrist Curl',
    exercise_type: 'isolation',
    primary_muscles: ['forearms'],
    secondary_muscles: [],
    alt_names: ['Barbell Wrist Curl', 'Dumbbell Wrist Curl'],
    description: '',
    weight_direction: 1,
  },
  {
    name: 'Reverse Wrist Curl',
    exercise_type: 'isolation',
    primary_muscles: ['forearms'],
    secondary_muscles: [],
    alt_names: ['Barbell Reverse Wrist Curl'],
    description: '',
    weight_direction: 1,
  },
  {
    name: 'Farmer\'s Carry',
    exercise_type: 'accessory',
    primary_muscles: ['forearms', 'traps'],
    secondary_muscles: ['core'],
    alt_names: ['Farmer\'s Walk'],
    description: '',
    weight_direction: 1,
  },
  {
    name: 'Plate Pinch',
    exercise_type: 'accessory',
    primary_muscles: ['forearms'],
    secondary_muscles: [],
    alt_names: [],
    description: '',
    weight_direction: 1,
  },
  {
    name: 'Dead Hang',
    exercise_type: 'accessory',
    primary_muscles: ['forearms'],
    secondary_muscles: ['lats'],
    alt_names: [],
    description: '',
    weight_direction: 1,
  },
  {
    name: 'Thick Bar Curl',
    exercise_type: 'isolation',
    primary_muscles: ['forearms', 'biceps'],
    secondary_muscles: [],
    alt_names: ['Fat Bar Curl'],
    description: '',
    weight_direction: 1,
  },
  {
    name: 'Behind-the-Back Wrist Curl',
    exercise_type: 'isolation',
    primary_muscles: ['forearms'],
    secondary_muscles: [],
    alt_names: [],
    description: '',
    weight_direction: 1,
  },
  {
    name: 'Suitcase Carry',
    exercise_type: 'accessory',
    primary_muscles: ['core', 'forearms'],
    secondary_muscles: ['traps'],
    alt_names: [],
    description: '',
    weight_direction: 1,
  },

  // ─── CORE ─────────────────────────────────────────────────────────────────────

  {
    name: 'Cable Crunch',
    exercise_type: 'isolation',
    primary_muscles: ['abs'],
    secondary_muscles: [],
    alt_names: ['Kneeling Cable Crunch'],
    description: '',
    weight_direction: 1,
  },
  {
    name: 'Machine Crunch',
    exercise_type: 'isolation',
    primary_muscles: ['abs'],
    secondary_muscles: [],
    alt_names: [],
    description: '',
    weight_direction: 1,
  },
  {
    name: 'Crunch',
    exercise_type: 'isolation',
    primary_muscles: ['abs'],
    secondary_muscles: [],
    alt_names: [],
    description: '',
    weight_direction: 1,
  },
  {
    name: 'Hanging Leg Raise',
    exercise_type: 'isolation',
    primary_muscles: ['abs'],
    secondary_muscles: ['core'],
    alt_names: ['Hanging Knee Raise'],
    description: '',
    weight_direction: 1,
  },
  {
    name: 'Lying Leg Raise',
    exercise_type: 'isolation',
    primary_muscles: ['abs'],
    secondary_muscles: ['core'],
    alt_names: ['Flat Bench Leg Raise'],
    description: '',
    weight_direction: 1,
  },

  // ─── FULL BODY / POWER ────────────────────────────────────────────────────────
  {
    name: 'Barbell Clean',
    exercise_type: 'compound',
    primary_muscles: ['legs'],
    secondary_muscles: ['traps', 'lower back', 'front delts'],
    alt_names: ['Power Clean'],
    description: '',
    weight_direction: 1,
  },
  {
    name: 'Barbell Snatch',
    exercise_type: 'compound',
    primary_muscles: ['legs'],
    secondary_muscles: ['traps', 'lower back', 'front delts'],
    alt_names: ['Power Snatch'],
    description: '',
    weight_direction: 1,
  },
  {
    name: 'Kettlebell Swing',
    exercise_type: 'accessory',
    primary_muscles: ['glutes', 'hamstrings'],
    secondary_muscles: ['lower back', 'core'],
    alt_names: ['KB Swing', 'Russian Kettlebell Swing'],
    description: '',
    weight_direction: 1,
  },
  {
    name: 'Kettlebell Snatch',
    exercise_type: 'compound',
    primary_muscles: ['glutes', 'quads'],
    secondary_muscles: ['traps', 'front delts'],
    alt_names: ['KB Snatch'],
    description: '',
    weight_direction: 1,
  },
];
